TRUNCATE TABLE public."Photos", public."Sightings", public."Species";

INSERT INTO public."Species"
VALUES
(1, 'Humpback Whale', 'Humpback whales are massive, growing to 17 metres in length. Their huge, dark bodies are flanked by enormous pectoral flippers growing up to around a third of their body length. Fantastic tools, they use their highly-manoeuvrable flippers for hunting by slapping the water and for swimming and even possibly regulating their body temperature. Equipped with a giant tail, this is their identifying feature. When they ‘fluke-up’ and dive, researchers can identify individual humpback whales by the markings on the underside of their tails. Moving to their heads and humpback whales are covered in funny knobbles. Unlike Auntie Mildred and more like Sooty the cat, these knobbles or bumps are called tubercles, and contain a single hair acting like a cat’s whiskers. Providing a sensory tool, these hairs feed back information about the whales’ surroundings.', 'https://uk.whales.org/wp-content/uploads/sites/6/bb-plugin/cache/humpback-whale-vanessa-mignon-300x200-landscape-8b2a22c58bffc689fa54da3bc4c9758b-.jpg', 'Humpback_Whale'),
(2, 'Blue Whale', 'The gentle giant of the sea, the blue whale is instantly recognisable with a long, streamlined shape, mottled blue or grey back and pale underbelly. They each have huge heads that are broad, long and have a unique U-shaped arch, and can reach up to a quarter of their body lengths in size. Famous for their sheer mass, blue whales glide effortlessly through the ocean, dwarfing all else in their path. Commanding awe, they grow to over 33 metres long (around 100ft) – twice as along as a T-Rex dinosaur. Even their calves are a whopping seven metres in length, weighing in the same as an adult African elephant.', 'https://uk.whales.org/wp-content/uploads/sites/6/bb-plugin/cache/blue-whale-andrew-sutton-2000-300x200-landscape-0512ca771a5421b182a0b075378cdce9-.jpg', 'Blue_Whale'),
(3, 'Gray Whale', 'Unlike any other large whale! As their name suggests, gray whales are grey in colour – although a more marbled than plain grey – with a relatively small, narrow head, which arches distinctively between the blowhole and snout. They have a robust body and flippers which are small and paddle-shaped. Instead of a dorsal fin there is a low hump with "knuckles" between the hump and the tail. Gray whales usually also have huge amounts of barnacles and whale lice attached predominantly to the head and body.', 'https://i.natgeofe.com/n/9703df2c-e98e-487a-884e-fc3a52b00c9d/W7RX5G.jpg', 'Gray_Whale'),
(4, 'Bryde''s Whale', 'The long and slender bodies of Bryde’s whales are a smoky blue-grey colour and often marbled with scars caused by parasites and cookie-cutter sharks. Each whale has a sickle-shaped dorsal fin about two-thirds of the way back along their body, and unlike other baleen whales, has three parallel ridges on the top of their head that make up a quarter of their entire body length. Filter feeders, they have between 40 and 70 throat pleats that allow their mouths to expand and 250 to 410 coarse baleen plates to sieve their food from seawater.', 'https://uk.whales.org/wp-content/uploads/sites/6/bb-plugin/cache/brydes-whale-jirayu-tour-ekkul-sg-300x200-landscape-adf7a0b7b26d7ec8a1756479fe5927ae-.jpg', 'Brydes_Whale'),
(5, 'Antartic Minke Whale', 'Graceful and nimble, Antarctic minke whales are perfectly suited to their environment. Their streamlined bodies enable them to glide through the water with ease and they use their long flippers to twist and turn. With two blowholes on top of their pointy heads, their chins are etched with deep grooves from their throats to their chests. Their skin is a shade of black or dark brown, and they have lovely pale bellies. Unlike common minke whales who have white markings on their flippers, Antarctic minke whales are unbanded. As far as whales go, they are actually pretty small too. With blue whales also among the rorqual family (the largest animal in the world), Antarctic minkes are dwarfed in comparison – generally no more than 10 metres long and weighing around 9 tonnes.', 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Minke_Whale_(NOAA).jpg', 'Antartic\_Minke\_Whale'),
(6, 'Beluga Whale', 'Born dark grey, with a bluish or brownish tinge that gets lighter with age, belugas turn pure white between 5 to 12 years of age. Beluga whales are unlike any other whale, dolphin or porpoise. A yellowish tinge can sometimes be seen on adult belugas, caused by a layer of algae growing on their skin. This yellowy hue is soon lost during summer moulting though – a rather unusual event for cetaceans – restoring them to their pearly glow. Given their choice of habitat, a beluga''s body needs to be robust and is wrapped in a thick layer of blubber. This often forms thick rubbery folds along the sides and belly, keeping them nice and warm.', 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/MSNBC/Components/Video/202005/WHALES.jpg', 'Beluga_Whale'),
(7, 'Sei Whale', 'The bodies of sei whales range in colouring from murky blues to steely greys to deep browns. Along their heads, a single ridge runs from the tip of the nose to two blowholes and set aloft their backs is a sickle-shaped dorsal fin. Growing up to 19.5 metres long, female sei whales are the larger of the two sexes, eclipsing their male counterparts by over 2 metres.', 'https://files.worldwildlife.org/wwfcmsprod/images/07.02.2012.Species.SeiWhale.hero/hero_small/658tkavct1_HI_257682.jpg', 'Sei_Whale'),
(8, 'Orca (Killer Whale)', 'If you’re an eight-metre-long, six-tonne predator, sneaking up on a tasty herring can be a tricky business. Which is where an orca’s black-and-white colouring is useful. This patterning works like camouflage, from above and below. It breaks up their appearance and makes them harder to see in the water. But above water, orcas’ tall dorsal fins make them easy to spot when they’re swimming close to the surface. Males have longer dorsal fins – up to two metres – that’s taller than most humans.', 'https://cdn.theatlantic.com/thumbor/ydanvjFnPfr7mUXDeAJFBw_oMH4=/0x214:4114x2528/960x540/media/img/mt/2019/04/shutterstock_554899423_1/original.jpg', 'Orca\_(Killer\_Whale)'),
(9, 'Narwhal', 'The most obvious thing to say is that males have a massive tusk which can grow up to 10 feet long. Most females don’t have a tusk and they look a bit like mottled grey beluga whales. Narwhals have a blotchy sausage-shaped body, a rounded head with no beak, a ridge on their backs rather than a fin and short blunt flippers with upcurled edges. They have odd-shaped tail flukes that look as though they have been put on backwards.', 'https://lawleypublishing.com/wp-content/uploads/2023/03/narwhal-swimming-in-the-sea-1024x691.jpg', 'Narwhal'),
(10, 'Hourglass Dolphin', 'Their Latin name ''cruciger'' means ''cross-bearing'' although this species is more commonly called the hourglass dolphin, due to the distinctive markings on the dolphin''s flanks. With a base colour of black (except for the belly which is white) there is a white stripe along each side of the body (starting just behind the mouth and extending all the way to the tail) which narrows under the dorsal fin creating the hourglass pattern. Hourglass dolphins also have quite distinctive fins which can be hooked and atop a broad base – some fins are even seen to be ‘swept-back’, the owners of these presumed to be adult males.', 'https://uk.whales.org/wp-content/uploads/sites/6/2019/04/hourglass-dolphin-sg-louise-cunningham2.jpg', 'Hourglass_Dolphin'),
(11, 'Atlantic Spotted Dolphin', 'Spotty! But the degree of spottiness and their colouration pattern varies with age and location. Their bodies are robust and generally dark grey on the top, lighter grey on the sides and white on the belly. When they are young, Atlantic spotted dolphins are dark grey with a pale white belly and it is easy to mistake them for small bottlenose dolphins. The flippers, dorsal fin and tail flukes usually remain unspotted. The dorsal fin is tall and curved. The beak is medium length, chunky and has a white tip. There is a well-defined crease between the beak and the melon (forehead).', 'https://www.ourbreathingplanet.com/wp-content/uploads/2018/10/Layer-0-342.jpg', 'Atlantic\_Spotted\_Dolphin'),
(12, 'Strap-Toothed Beaked Whale', 'The strap-toothed beaked whales’ body is black in colouration with a large white patch on the top at the front, which goes around the neck and down under the chest. They have a has slightly rounded ‘melon’ where the forehead slopes down to one of the longest beaks (slender and pale in colour) of all beaked whales. A rather distinctive black patch of colour is found over the eyes and across the forehead. Strap-toothed beaked whales have small, narrow flippers and a small dorsal fin set quite far back on the body. As with other beaked whales, male strap-toothed whales often have white scratches and scars on their bodies, suggesting competition amongst rivals.', 'https://cmst.curtin.edu.au/wp-content/uploads/sites/4/2017/06/Mesoplodon-layardii-CWR-588x390.jpg', 'Strap-Toothed\_Beaked\_Whale'),
(13, 'Southern Bottlenose Whale', 'The Southern bottlenose whale is a large, robust beaked whale. It has a bulbous melon, which becomes larger as the males age. The forehead is steep, and the stubby beak is well defined resembling the beak of several dolphin species. Two small conical teeth erupt at the tip of the lower jaw in males although these are not always seen outside of the jaw. The body is pale tan or olive brown in colour with extensive scarring, especially on older males and whitish spots on the belly and flanks are likely to be scars resulting from the bite of cookie cutter sharks. The head, face, and belly of the southern bottlenose whale are a paler cream colour and in general, females are darker with a smaller, less bulbous, melon. As with other species of beaked whale they have ''flipper pockets'' for when they dive, and a small, pointed, triangular or falcate dorsal fin set well back on the body.', 'https://www.whaletrail.co.za/images/southern-bottlenose-whale-590x390.jpg', 'Southern\_Bottlenose\_Whale'),
(14, 'Pygmy Right Whale', 'Pygmy right whales have small, flat and ridged heads that are heavily accentuated by their strongly arched jawlines. Extremely pronounced, their jawlines are unmistakable and become more exaggerated as they grow older. Filter-feeding whales, pygmy right whales have an ivory-coloured baleen that is threaded with around 213 to 230 plates on each side. Unlike right whales, pygmy right whales have sleeker, more streamlined bodies that are topped with a small, sickle-shaped dorsal fin. On either side they have small, narrow and rounded flippers and underneath they have beautiful pale highlighting that runs from their lower jaw, along the belly and all the way to the tail. With an absence of lumpy callosities and resembling rorqual whales, pygmy right whales are sometimes confused with minke whales when seen in the wild.', 'https://us.whales.org/wp-content/uploads/sites/2/2019/06/pygmy-right-whale-sg-robert-pitman.jpg', 'Pygmy\_Right\_Whale'),
(15, 'Long-Finned Pilot Whale', 'As their name suggests, they have two very long flippers; they are crescent-shaped and have pointy tips. Adult pilot whales are black or dark grey and have a lighter grey saddle patch on the back behind the dorsal fin and a white anchor-shaped patch on the underside. Pilot whale babies are paler coloured. Pilot whales are long, robust whales and have a thick-set, curved (sometimes hooked), and very prominent dorsal fin. The head is bulbous with no beak. Male pilot whales are larger than females, and they have a more bulbous forehead and chunkier dorsal fin.', 'https://oceana.org/wp-content/uploads/sites/18/32_2.jpg', 'Long-Finned\_Pilot\_Whale'),
(16, 'Fin Whale', 'Truly handsome individuals, fin whales have long, slender bodies that can grow up to a whopping 80 feet in length. With a distinct ridge running behind the dorsal fin, in the USA they have earned themselves the nickname “razorbacks” and cut through the water with ease. Like other baleen whales, fin whales have expandable pleats that allow them to take in huge amounts of water and food. They then sieve the water out through their baleen plates before ingesting their delicious meal, consuming up to 2,000kg of krill in a day.', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Finhval_(1).jpg', 'Fin_Whale');

INSERT INTO public."Sightings"
    ("Latitude", "Longitude", "Date", "Description", "SpeciesId", "Approved", "UserId")
VALUES
    (51.506523, -0.077999, '09/11/2023', 'Whale spotted in the Thames', 1, TRUE, 1),
    (57.28373, -4.470851, '09/11/2023', 'Nessie!', 1, TRUE, 1),
    (35.315483, 136.1458, '09/11/2023', '鯨', 1, FALSE, 1),
    (5.405249, -152.760568, '09/11/2023', 'A majestic humpback whale breaching in the sunlight.', 1, FALSE, 1),
    (-36.883362, -145.107862, '08/11/2023', 'A playful pod of dolphins swimming alongside a gentle gray whale.', 1, FALSE, 1),
    (24.662759, -179.485124, '07/11/2023', 'A curious beluga whale, known for its distinctive white coloring.', 1, TRUE, 1),
    (-3.148761, -11.71846, '06/11/2023', 'A massive blue whale, the largest animal on Earth, gracefully gliding through the ocean.', 1, TRUE, 1),
    (-10.301309, -60.784694, '05/11/2023', 'A close-up of a killer whale, showcasing its striking black and white pattern.', 1, TRUE, 1),
    (-18.663142, -94.593933, '04/11/2023', 'Two friendly narwhals, known for their long, spiral tusks, swimming together.', 1, FALSE, 1),
    (33.502385, -31.561806, '25/10/2023', 'A family of orcas, also known as killer whales, hunting together.', 1, FALSE, 1),
    (-47.22574, -39.246788, '14/10/2023', 'An adorable baby whale calf swimming alongside its mother.', 1, FALSE, 1),
    (2.617893, -62.166993, '02/10/2023', 'A rare sighting of a sperm whale, with its large, square head.', 1, TRUE, 1),
    (-35.697293, -134.209864, '19/09/2023', 'A group of humpback whales engaged in bubble-net feeding.', 1, TRUE, 1),
    (15.80395, -102.703247, '05/09/2023', 'A breaching minke whale, leaping out of the water with elegance.', 1, TRUE, 1),
    (-20.815488, -144.931229, '21/08/2023', 'A serene scene of a gray whale gliding through calm waters.', 1, TRUE, 1),
    (45.697439, -89.165199, '05/08/2023', 'A pod of pilot whales surfacing in unison.', 1, FALSE, 1),
    (37.66826, -79.067946, '19/07/2023', 'A close encounter with a curious fin whale.', 1, TRUE, 1),
    (-11.724918, -162.936689, '01/07/2023', 'A picturesque view of a peaceful whale shark, the world''s largest fish.', 1, FALSE, 1),
    (-25.587501, -44.727909, '12/06/2023', 'A stunning shot of a sei whale with its distinctive dorsal fin.', 1, FALSE, 1),
    (6.291582, -57.184805, '23/05/2023', 'An artistic portrayal of a mystical and elusive beaked whale.', 1, FALSE, 1),
    (-19.330142, -97.422455, '02/05/2023', 'A charming image of a smiling false killer whale.', 1, FALSE, 1),
    (30.019302, -48.475617, '10/04/2023', 'An intimate moment between a mother and calf right whale.', 1, FALSE, 1),
    (-38.543412, -149.444209, '18/03/2023', 'A group of playful spinner dolphins leaping out of the water.', 1, TRUE, 1),
    (-29.097924, -73.666938, '22/02/2023', 'A breathtaking underwater view of a breaching humpback whale.', 1, FALSE, 1),
    (-10.819979, -127.288041, '28/01/2023', 'A tranquil scene of a lazy right whale lounging near the surface.', 1, FALSE, 1),
    (-46.664148, -175.127072, '02/01/2023', 'A heartwarming image of a baby narwhal and its unique tusk.', 1, FALSE, 1),
    (38.194419, -54.825209, '06/12/2022', 'A regal depiction of a killer whale in the wild.', 1, FALSE, 1);

DO $$
DECLARE
FirstSightingId INT;
BEGIN

SELECT COALESCE(MIN("Id"), 0) INTO FirstSightingId FROM public."Sightings";

INSERT INTO public."Photos"
    ("Image", "SightingId")
VALUES
    ('https://th.bing.com/th/id/R.c22c0a1d980952a6c57297a4d5a8f1d2?rik=MJTE10TaKcZYmw&riu=http%3A%2F%2Fassets.wwf.org.uk%2Fimg%2Foriginal%2F03_wwf_whale_a_geoff_caddick__pa_1_.jpg&ehk=hLuj7uqtxIei4M%2FH52O0ODRH6Q9XZ4fIEJjgrKTSGb4%3D&risl=&pid=ImgRaw&r=0', FirstSightingId),
    ('https://www.thescottishsun.co.uk/wp-content/uploads/sites/2/2020/12/NINTCHDBPICT000315662932.jpg?strip=all&quality=100&w=1200&h=800&crop=1', FirstSightingId + 1),
    ('https://c.files.bbci.co.uk/9A72/production/_103283593_gettyimages-496786536.jpg', FirstSightingId + 2),
    ('https://th-thumbnailer.cdn-si-edu.com/twjiv9qG0kLGDFT4aaLn8t2FDCU=/fit-in/1072x0/https://tf-cmsv2-photocontest-smithsonianmag-prod-approved.s3.amazonaws.com/eb08062c-918b-4807-a5c3-fc67e7c3ee94.jpg', FirstSightingId + 3),
    ('https://marinesanctuary.org/wp-content/uploads/2020/04/MBNMS-dolphins-BobTalbot.jpg', FirstSightingId + 4),
    ('https://th.bing.com/th/id/OIP.zs5LzGxsrWBfJ_iEfx2FcAHaE7?pid=ImgDet&rs=1', FirstSightingId + 5),
    ('https://th.bing.com/th/id/OIP.Ci9c66vAPTR3MVomj91Z1QHaDt?pid=ImgDet&rs=1', FirstSightingId + 6),
    ('https://www.aboutanimals.com/images/killer-whale-dorsal-fin-820x448.jpg?c14113', FirstSightingId + 7),
    ('https://1.bp.blogspot.com/-aBEyr01-oAE/YFNf5E9MzLI/AAAAAAAAL6k/QNd7HVFTCOIMdYO3-1fef0YfIGzWAkINQCLcBGAsYHQ/s1600/Narwhal%2BUnicorn%2Bof%2Bthe%2Bsea.jpg', FirstSightingId + 8),
    ('https://www.worldatlas.com/r/w1200-q80/upload/8b/69/a8/shutterstock-631060871.jpg', FirstSightingId + 9),
    ('https://images.fineartamerica.com/images-medium-large/mom-and-calf-humpback-whales-david-olsen.jpg', FirstSightingId + 10),
    ('https://th.bing.com/th/id/R.098f15c0fbb798e7d9566750a9ddd1f5?rik=iCvLlTcGTbmOzg&riu=http%3A%2F%2Fwww.lazerhorse.org%2Fwp-content%2Fuploads%2F2014%2F10%2FSperm-Whale-Swimming-Rare.jpg&ehk=Dr81F7bKzgK4gZKgKKVx9I7I7n9tHOa%2BTiKrmZXxqiY%3D&risl=&pid=ImgRaw&r=0', FirstSightingId + 11),
    ('https://images.fineartamerica.com/images-medium-large-5/humpback-whales-bubble-net-feeding-hiroya-minakuchi.jpg', FirstSightingId + 12),
    ('https://i.pinimg.com/474x/53/36/f5/5336f516018d0f20e7ac2ad2f7d73b10--minke-whale-a-whale.jpg', FirstSightingId + 13),
    ('https://th.bing.com/th/id/OIP.sfOo3CADMsWoGilualWikAHaE9?pid=ImgDet&rs=1', FirstSightingId + 14),
    ('https://media.istockphoto.com/photos/pilot-whale-pod-picture-id616865302?k=6&m=616865302&s=612x612&w=0&h=JSy_ZdPdVLYg41RXNCj3b_PGYiImSoGT2HJISV74-fI=', FirstSightingId + 15),
    ('https://i.pinimg.com/originals/2a/b9/d9/2ab9d9e399709e1309a05e5abc169ecc.jpg', FirstSightingId + 16),
    ('https://helios-i.mashable.com/imagery/articles/02RCbD5gUjviyFQZNFO087v/hero-image.fill.size_1248x702.v1658850223.jpg', FirstSightingId + 17),
    ('https://www.antarctica.gov.au/site/assets/files/45706/20110408_peterduley_seiwhale_feed_img7420_permit775-1875.1024x0.jpg', FirstSightingId + 18),
    ('https://i.pinimg.com/736x/db/d0/59/dbd059813680b3e2e0492677c06c0f9f--whale-art-big-whale.jpg', FirstSightingId + 19),
    ('https://pix.avax.news/avaxnews/d0/32/000132d0.jpeg', FirstSightingId + 20),
    ('https://th.bing.com/th/id/R.98401e4ec3844feb3b553029305637c1?rik=C3TmKFvNqJsv4g&riu=http%3A%2F%2F2.bp.blogspot.com%2F-DF3fNpEKOJc%2FT2zdbVM-anI%2FAAAAAAAAEZI%2FqaT-8UQHeNM%2Fs1600%2FWhalesMomBaby.jpg&ehk=xIu1%2BADOPnyz86QPboQdmO%2Bn7E7M%2BCYnj%2BD74hOCaWY%3D&risl=&pid=ImgRaw&r=0', FirstSightingId + 21),
    ('https://4.bp.blogspot.com/-xXr2quvhuXM/Uv-jqGVik7I/AAAAAAAAO1Q/XTLFZeGEP-A/s1600/Dolphins1.JPG', FirstSightingId + 22),
    ('https://i.pinimg.com/originals/3d/1b/cd/3d1bcd76a8135ecd647c013191a3c02f.jpg', FirstSightingId + 23),
    ('https://th.bing.com/th/id/OIP.jLt0mqRYPo1VPqI7FL52FwHaE7?pid=ImgDet&rs=1', FirstSightingId + 24),
    ('https://th.bing.com/th/id/OIP.P-LEqpchJcY8VZVcpA3KkgHaDd?pid=ImgDet&rs=1', FirstSightingId + 25),
    ('https://th.bing.com/th/id/OIP.zzbOC3JTPPI2aohONC60swHaJF?pid=ImgDet&rs=1', FirstSightingId + 26);

END $$;